### ISSUE TITLE
Bundle instapy-chromedriver as a dependency

### ISSUE THREAD

**Issue by ishandutta2007** [timgrossmann/InstaPy-sex-classification#2]
Currently you need to explicitly add it to PATH if not already done. This was the error for me.
Ideally it should work out of the box like [InstaPy](https://github.com/timgrossmann/InstaPy).

> Traceback (most recent call last):
>   File "classify_profiles.py", line 21, in <module>
>     browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
>     self.service.start()
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
>     os.path.basename(self.path), self.start_error_message)
> selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
> 
>

**Comment by timgrossmann** [comment]
@ishandutta2007 Good point, this should be doable pretty easily but since we are currently not working on this at all (I might write my BA Thesis about this topic starting at the end of the year) I think we should focus our time and energy on InstaPy.
What do you think? 😊 

> Especially since the code is pretty outdated and probably has to be recreated.
